name = "digital-visibility-astro"
compatibility_date = "2024-01-01"

# KV Namespace for funnel data
[[kv_namespaces]]
binding = "FUNNEL_DATA"
id = "7a8832a631674679aa52f4f490e0c769"
preview_id = "7a8832a631674679aa52f4f490e0c769"

# Cron Triggers for data aggregation
[[triggers]]
crons = ["0 */12 * * *"]  # Every 12 hours

# Environment variables (set these in Cloudflare dashboard)
[vars]
# GA4_ID = "G-T7HFBLX1X1"
# CLARITY_ID = "trt5xn1qai"
# CLAUDE_API_KEY = "your-claude-api-key"
# ADMIN_USER = "admin"
# ADMIN_PASS = "your-secure-password"

# Pages configuration
[env.production]
name = "digital-visibility-astro"

[env.preview]
name = "digital-visibility-astro-preview"